version: '3.1'

services:
  stats-server:
    container_name: stats-server
    build: ewm-stats-service/service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistics
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statistics
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    container_name: emw-service
    build: ewm-main-service
    ports:
      - "8080:8080"